// @index('../../client/campaign/*.jsx', (f, _) => `export { default as ${_.pascalCase(f.name)} } from '${f.path}'`)
export { default as Actions } from '../../client/campaign/actions'
export { default as Characters } from '../../client/campaign/characters'
export { default as Create } from '../../client/campaign/create'
export { default as Edit } from '../../client/campaign/edit'
export { default as Homepage } from '../../client/campaign/homepage'
export { default as Menu } from '../../client/campaign/menu'
export { default as Profile } from '../../client/campaign/profile'
export { default as Recruiter } from '../../client/campaign/recruiter'
export { default as Routes } from '../../client/campaign/routes'
export { default as Save } from '../../client/campaign/save'
export { default as Sessions } from '../../client/campaign/sessions'
export { default as Settings } from '../../client/campaign/settings'
export { default as Summaries } from '../../client/campaign/summaries'
export { default as Summarize } from '../../client/campaign/summarize'
export { default as Summary } from '../../client/campaign/summary'
export { default as Xp } from '../../client/campaign/xp'
