// @index('../../client/character/*.jsx', (f, _) => `export { default as ${_.pascalCase(f.name)} } from '${f.path}'`)
export { default as Ability } from '../../client/character/ability'
export { default as Ac } from '../../client/character/ac'
export { default as Actions } from '../../client/character/actions'
export { default as Alignment } from '../../client/character/alignment'
export { default as Attack } from '../../client/character/attack'
export { default as Attacks } from '../../client/character/attacks'
export { default as Avatar } from '../../client/character/avatar'
export { default as Bio } from '../../client/character/bio'
export { default as Die } from '../../client/character/die'
export { default as Features } from '../../client/character/features'
export { default as Hd } from '../../client/character/hd'
export { default as Health } from '../../client/character/health'
export { default as Homepage } from '../../client/character/homepage'
export { default as Initiative } from '../../client/character/initiative'
export { default as Injury } from '../../client/character/injury'
export { default as Inventory } from '../../client/character/inventory'
export { default as Menu } from '../../client/character/menu'
export { default as Metadata } from '../../client/character/metadata'
export { default as Parts } from '../../client/character/parts'
export { default as Powers } from '../../client/character/powers'
export { default as Proficiency } from '../../client/character/proficiency'
export { default as Profile } from '../../client/character/profile'
export { default as Save } from '../../client/character/save'
export { default as Skill } from '../../client/character/skill'
export { default as Skills } from '../../client/character/skills'
export { default as Tier } from '../../client/character/tier'
export { default as Xp } from '../../client/character/xp'
//@endindex

export * as Editor from "./editor"