// @index('../../interface/components/*.jsx', (f, _) => `export { default as ${_.pascalCase(f.name)} } from '${f.path}'`)
export { default as Action } from '../../interface/components/action'
export { default as Card } from '../../interface/components/card'
export { default as Description } from '../../interface/components/description'
export { default as Gallery } from '../../interface/components/gallery'
export { default as Link } from '../../interface/components/link'
export { default as List } from '../../interface/components/list'
export { default as Metadata } from '../../interface/components/metadata'
export { default as Organizer } from '../../interface/components/organizer'
export { default as Rule } from '../../interface/components/rule'
export { default as Table } from '../../interface/components/table'
export { default as Tables } from '../../interface/components/tables'
export { default as Tag } from '../../interface/components/tag'
export { default as Tree } from '../../interface/components/tree'
